suppressMessages(library(XML))
suppressMessages(library(stringr))
suppressMessages(library(lubridate))
suppressMessages(library(base64enc))
suppressMessages(library(zoo))
suppressMessages(library(xts))
suppressMessages(library(httr))
suppressMessages(library(base64enc))
suppressMessages(library(foreach))
suppressMessages(library(doParallel))

suppressMessages(library(tsconvert))